Task/SP3HFT1
netomantonio/entretien-fe pull request #48
Opened 2023-06-23 02:08 UTC by leonardowrobel

- Rotas para a dash na barra de navegação.

2023-06-23 13:46 UTC, netomantonio requested changes

2023-06-23 13:46 UTC, netomantonio commented on src/components/Dashboard/Recruiter/index.vue
> +    <DashboardHeader subtitle="Recruiter"/>
Esse tipo de informação deve ser em português e também manter o padrão colocado no exemplo do Admin "Painel do Administrador"

2023-06-23 23:04 UTC, netomantonio approved these changes

2023-06-23 23:04 UTC, merged

2023-06-24 00:38 UTC, leonardowrobel commented
![](https://github.trello.services/images/mini-trello-icon.png) [#SP3HFT1 - Rota para dashboard do manager não está navegável após realizar o login e entrar em outra pagina](https://trello.com/c/bPqaQTzc/28-sp3hft1-rota-para-dashboard-do-manager-n%C3%A3o-est%C3%A1-naveg%C3%A1vel-ap%C3%B3s-realizar-o-login-e-entrar-em-outra-pagina)